### ISSUE TITLE
Level 0 - Team integration and base knowledge

### ISSUE THREAD

**Issue by Soap2G** [atlas-outreach-data-tools/root-browser#2]
Integrate with the team's main tools for communication and development.

- [x] Get a CERN account
- [x] Join the [ATLAS Open Data mattermost channel](https://mattermost.web.cern.ch/signup_user_complete/?id=pncieswuf3fzxfdbmtgi84p9ah&md=link&sbr=su)
- [x] Familiarise with [git](https://swcarpentry.github.io/git-novice/) (and create an account if needed)
- [x] Familiarise with [scikit-hep's `uproot`](https://hsf-training.github.io/hsf-training-uproot-webpage/index.html) and the [ROOT project](https://root.cern/learn/)
- [x] Familiarise with [Docker](https://hsf-training.github.io/hsf-training-docker/index.html)

**Comment by TukeCS** [comment]
Alright, 
- i looked at [scikit-hep's uproot](https://hsf-training.github.io/hsf-training-uproot-webpage/index.html) and the [ROOT project](https://root.cern/learn/)
- i looked at the Docker and Podman tutorials [Docker](https://hsf-training.github.io/hsf-training-docker/index.html)
